// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project.Tereza.Infrastructure.DBContext;

#nullable disable

namespace Project.Tereza.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project.Tereza.Core.Need", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCovered")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Need");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82d257a5-d72b-4f08-bcf2-76ebdc958b5f"),
                            Count = 1,
                            Description = "Need laptop for working needs.",
                            IsCovered = false,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = new Guid("b47fdb0a-76d4-4b89-bf20-9cecfa4f4f82"),
                            Count = 1,
                            Description = "I need food for my cat, please help!",
                            IsCovered = false,
                            Name = "Royal Canin Sphyncx 2 kg"
                        },
                        new
                        {
                            Id = new Guid("a961067e-c777-42c2-8fee-71180d750bd7"),
                            Count = 3,
                            Description = "Please, I can't find this drug in retail",
                            IsCovered = false,
                            Name = "Aspirin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
